DataVista.Web/Areas/Admin/Controllers/ConfigurationController.cs
using System.Threading.Tasks;
using DataVista.DataAccess.Models;
using DataVista.Models.ViewModels;
using DataVista.Repository.IRepository;
using DataVista.Utility;
using Microsoft.AspNetCore.Mvc;
using Microsoft.VisualBasic;

namespace DataVista.Web.Areas.Admin.Controllers;

public class ConfigurationController : Controller
{
    #region--Constructor--

    private readonly DataVistaContext _db;
    private readonly IUnitOfWork _unitOfWork;
    private readonly IWebHostEnvironment _webHostEnvironment;
    public ConfigurationController(DataVistaContext db, IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
    {
        _db = db;
        _unitOfWork = unitOfWork;
        _webHostEnvironment = webHostEnvironment;
    }

    #endregion


    #region--Role--

    #region--GET METHOD--
    public async Task<IActionResult> Role(int? id)
    {
        var roleVM = new RoleVM();
        if (id.HasValue && id != 0)
        {
            var rol = await _unitOfWork.Role.GetFirstOrDefaultAsync(ro => ro.IsDeleted == false && ro.Id == id, IsTracked: false);
            if (rol == null)
            {
                TempData["error"] = STATIC_DATASETS.MError;
                return RedirectToAction();
            }
            roleVM.Role = rol;
        }
        return View(roleVM);
    }

    #endregion

    #region--View Table--
    public async Task<IActionResult> GetAllRole()
    {
        var dataList = await _unitOfWork.Role.GetAllAsync(r => r.IsDeleted == false);
        return Json(new { data = dataList });
    }

    #endregion

    #region--Delete--

    [HttpDelete]
    public async Task<IActionResult> DeleteRole(int id)
    {

        //------------Delete Data Code Below-----------
        var objFromDb = await _unitOfWork.Role
         .GetFirstOrDefaultAsync(r => r.IsDeleted == false && r.Id == id);

        if (objFromDb == null)
        {
            return Json(new { success = false, message = STATIC_DATASETS.MNotFound });
        }
        objFromDb.IsDeleted = true;
        //_unitOfWork.Role.Update(objFromDb);
        await _unitOfWork.SaveAsync();
        return Json(new { success = true, message = STATIC_DATASETS.MDelete });

    }

    #endregion




    #endregion


}

DataVista.Web/Areas/Admin/Controllers/CredentialController.cs
using Microsoft.AspNetCore.Mvc;

namespace DataVista.Web.Areas.Admin.Controllers;

public class CredentialController : Controller
{
    public IActionResult Login()
    {
        return View();
    }
}

DataVista.Web/Areas/Admin/Controllers/UserController.cs
using DataVista.DataAccess.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using DataVista.Repository.IRepository;

namespace DataVista.Web.Areas.Admin.Controllers;

public class UserController : Controller
{

    private readonly IUnitOfWork _unitOfWork;

    private readonly DataVistaContext _db;
    private readonly IWebHostEnvironment _webHostEnvironment;
    private readonly IConfiguration _configuration;
    private readonly IEmailSender _emailSender;

    public UserController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment, DataVistaContext db, IEmailSender emailSender, IConfiguration configuration)
    {
        _unitOfWork = unitOfWork;
        _webHostEnvironment = webHostEnvironment;
        _db = db;
        _configuration = configuration;
        _emailSender = emailSender;
    }
    public IActionResult User()
    {
        return View();
    }
}

DataVista.Web/Areas/Admin/Views/Configuration/Role.cshtml
@model RoleVM
@{
	ViewData["Title"] = "Role";
}


<div class="main-content">
	<div class="page-content">
		<div class="container-fluid">
			<!-- start page title -->
			<div class="row">
				<div class="col-12">
					<div class="page-title-box d-sm-flex align-items-center justify-content-between">
						<h4 class="mb-sm-0 font-size-18">Role</h4>

						<div class="page-title-right">
							<ol class="breadcrumb m-0">
								<li class="breadcrumb-item"><a asp-controller="Admin" asp-action="Dashboard">Home</a></li>
								<li class="breadcrumb-item active">Role</li>
							</ol>
						</div>
					</div>
				</div>
			</div>
		</div>

		<!-- Form -->
		<div class="row">
			<div class="col-lg-12">
				<div class="card">
					<div class="card-body">
						<h2 class="card-title mb-4">
							@(Model.Role.Id == 0 ? "Enter Role" : "Update Role")
						</h2>
						<form method="post" enctype="multipart/form-data">
							<input type="hidden" asp-for="Role.Id" value="@Model.Role.Id" />
							<div class="row">
								<div class="col-md-6">
									<div class="mb-3">
										<label asp-for="Role.Name" class="form-label">Role Name*</label>
										<input asp-for="Role.Name" type="text" class="form-control" placeholder="Enter Role"
											   maxlength="300" required />
										<span asp-validation-for="Role.Name" class="text-danger"></span>
									</div>
								</div>
							</div>

							@if (Model.Role.Id == 0)
							{
								<div class="row mt-3">
									<div class=" col-lg-12 text-center">
										<button class="btn btn-success w-md" type="submit">Save</button>
										<a  asp-area="Admin" asp-controller="Configuration" asp-action="Role" class="btn btn-danger w-md ms-2">Reset</a>
									</div>
								</div>
							}
							else
							{
								<div class="row mt-3">
									<div class=" col-lg-12 text-center">
										<button class="btn btn-warning w-md" type="submit">Update</button>
										<a asp-area="Admin" asp-controller="Configuration" asp-action="Role" class="btn btn-danger w-md ms-2">Reset</a>
									</div>
								</div>
							}
						</form>
					</div>
				</div>
				<!-- end select2 -->
			</div>
		</div>
		<!--Data List-->
		<div class="row">
			<div class="col-12">
				<div class="card">
					<div class="card-body">
						<h2 class="card-title">List of Role</h2>
						<table id="datatable" class="table table-bordered dt-responsive nowrap w-100">
							<thead class="Tiall">
								<tr>
									<th>Serial No.</th>
									<th>Name</th>
									<th>Action</th>
								</tr>
							</thead>
						</table>
					</div>
				</div>
			</div> <!-- end col -->
		</div>
		<!-- end DataTable -->
	</div>



</div>
<!-- end main content-->
@section Scripts {
	<script type="module" src="~/js/Configure/role.js" asp-append-version="true"></script>
}

DataVista.Web/Areas/Admin/Views/Credential/Login.cshtml
@{
    ViewData["Title"] = "Login";
}


<div class="account-pages my-5 pt-sm-5">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8 col-lg-6 col-xl-5">
                <div class="card overflow-hidden">
                    <div class="bg-primary bg-soft">
                        <div class="row">
                            <div class="col-12">
                                <div class="text-primary p-4 text-center">

                                    <h5 class="text-primary mt-3">login</h5>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-body pt-0">

                        <div class="p-2">
                            <form enctype="multipart/form-data" method="post">
                                @*  <div class="mb-3">
                                    <label for="useremail" class="form-label">Username</label>
                                    <input type="text" class="form-control" asp-for="Email" placeholder="Enter username" required>
                                    <div class="invalid-feedback">
                                        Enter username
                                    </div>
                                </div> *@


                                <div class="mb-3">
                                    <label for="useremail" class="form-label">Username</label>
                                    <input type="text" class="form-control" placeholder="Enter username" required>
                                    <div class="invalid-feedback">
                                        Enter username
                                    </div>
                                </div>

                                @*  <div class="mb-3">
                                    <label class="form-label">Password</label>
                                    <div class="input-group auth-pass-inputgroup">
                                        <input type="password" class="form-control" asp-for="Password" placeholder="Enter password" aria-label="Password" aria-describedby="password-addon" required>
                                        <button class="btn btn-light " type="button" id="password-addon"><i class="mdi mdi-eye-outline"></i></button>
                                        <div class="invalid-feedback">
                                            Enter password
                                        </div>
                                    </div>
                                </div> *@

                                <div class="mb-3">
                                    <label class="form-label">Password</label>
                                    <div class="input-group auth-pass-inputgroup">
                                        <input type="password" class="form-control" placeholder="Enter password" aria-label="Password" aria-describedby="password-addon" required>
                                        <button class="btn btn-light " type="button" id="password-addon"><i class="mdi mdi-eye-outline"></i></button>
                                        <div class="invalid-feedback">
                                            Enter password
                                        </div>
                                    </div>
                                </div>

                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" id="remember-check">
                                    <label class="form-check-label" for="remember-check">
                                        Remember me
                                    </label>
                                </div>
                                <div class="mt-3 d-grid">
                                    @* <button type="submit" class="btn btn-success waves-effect waves-light">Log In</button> *@
                                    <a class="btn btn-primary waves-effect waves-light" asp-area="Admin" asp-controller="User" asp-action="User">Log In</a>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>


            </div>
        </div>
    </div>
</div>

DataVista.Web/Areas/Admin/Views/User/User.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

DataVista.Web/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
	<meta name="viewport" content="width=device-width" />
	<title>@ViewBag.DataVista</title>
	<!-- Fonts and icons -->
	<script src="~/DataVistaTemplate/assets/js/plugin/webfont/webfont.min.js"></script>
	<!-- CSS Files -->
	<link rel="stylesheet" href="~/DataVistaTemplate/assets/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/DataVistaTemplate/assets/css/plugins.min.css" />
	<link rel="stylesheet" href="~/DataVistaTemplate/assets/css/kaiadmin.min.css" />

</head>
<body>

	<div class="wrapper">
		<!-- Sidebar -->
		<div class="sidebar" data-background-color="dark">
			<div class="sidebar-logo">
				<!-- Logo Header -->
				<div class="logo-header" data-background-color="dark">
					<a href="index.html" class="logo">
						@* <img src="~/DataVistaTemplate/assets/img/kaiadmin/logo_light.svg"
							 alt="navbar brand"
							 class="navbar-brand"
							 height="20" /> *@
					</a>
					<div class="nav-toggle">
						<button class="btn btn-toggle toggle-sidebar">
							<i class="gg-menu-right"></i>
						</button>
						<button class="btn btn-toggle sidenav-toggler">
							<i class="gg-menu-left"></i>
						</button>
					</div>
					<button class="topbar-toggler more">
						<i class="gg-more-vertical-alt"></i>
					</button>
				</div>
				<!-- End Logo Header -->
			</div>
			<div class="sidebar-wrapper scrollbar scrollbar-inner">
				<div class="sidebar-content">


					<ul class="nav nav-secondary">

						<li class="nav-item">

							<a data-bs-toggle="collapse" href="#base">
								<i class="fas fa-layer-group"></i>
								<p>User Registration</p>
								<span class="caret"></span>
							</a>
							<div class="collapse" id="base">
								<ul class="nav nav-collapse">
									<li><a asp-controller="Admin" asp-action="UserRegistration" key="t-default">Registration</a></li>
								</ul>
							</div>

						</li>

					</ul>


				</div>
			</div>
		</div>
		<!-- End Sidebar -->

		<div class="main-panel">
			<div class="main-header">
				<div class="main-header-logo">
					<!-- Logo Header -->
					<div class="logo-header" data-background-color="dark">
						<a href="index.html" class="logo">
							<img src="~/DataVistaTemplate/assets/img/kaiadmin/logo_light.svg"
								 alt="navbar brand"
								 class="navbar-brand"
								 height="20" />
						</a>
						<div class="nav-toggle">
							<button class="btn btn-toggle toggle-sidebar">
								<i class="gg-menu-right"></i>
							</button>
							<button class="btn btn-toggle sidenav-toggler">
								<i class="gg-menu-left"></i>
							</button>
						</div>
						<button class="topbar-toggler more">
							<i class="gg-more-vertical-alt"></i>
						</button>
					</div>
					<!-- End Logo Header -->
				</div>



				<!-- Navbar Header -->
				<nav class="navbar navbar-header navbar-header-transparent navbar-expand-lg border-bottom">
					<div class="container-fluid">
						<nav class="navbar navbar-header-left navbar-expand-lg navbar-form nav-search p-0 d-none d-lg-flex">
							<div class="input-group">
								<div class="input-group-prepend">
									<button type="submit" class="btn btn-search pe-1">
										<i class="fa fa-search search-icon"></i>
									</button>
								</div>
								<input type="text"
									   placeholder="Search ..."
									   class="form-control" />
							</div>
						</nav>

						<ul class="navbar-nav topbar-nav ms-md-auto align-items-center">
							<li class="nav-item topbar-icon dropdown hidden-caret d-flex d-lg-none">
								<a class="nav-link dropdown-toggle"
								   data-bs-toggle="dropdown"
								   href="#"
								   role="button"
								   aria-expanded="false"
								   aria-haspopup="true">
									<i class="fa fa-search"></i>
								</a>
								<ul class="dropdown-menu dropdown-search animated fadeIn">
									<form class="navbar-left navbar-form nav-search">
										<div class="input-group">
											<input type="text"
												   placeholder="Search ..."
												   class="form-control" />
										</div>
									</form>
								</ul>
							</li>

							<li class="nav-item topbar-user dropdown hidden-caret">
								<a class="dropdown-toggle profile-pic"
								   data-bs-toggle="dropdown"
								   href="#"
								   aria-expanded="false">
									<div class="avatar-sm">
										<img src="~/DataVistaTemplate/assets/img/profile.jpg"
											 alt="..."
											 class="avatar-img rounded-circle" />
									</div>
									<span class="profile-username">
										<span class="op-7">Hi,</span>
										<span class="fw-bold">Admin</span>
									</span>
								</a>
								<ul class="dropdown-menu dropdown-user animated fadeIn">
									<div class="dropdown-user-scroll scrollbar-outer">
									<li>
										<div class="user-box">
											<div class="avatar-lg">
												<img src="~/DataVistaTemplate/assets/img/profile.jpg"
													 alt="image profile"
													 class="avatar-img rounded" />
											</div>
											<div class="u-text">
												<h4>Hizrian</h4>
												<p class="text-muted">hello@example.com</p>
												 
											</div>
										</div>
									</li>
									<li>
										<div class="dropdown-divider"></div>
										<a class="dropdown-item" href="#">My Profile</a>
										<a class="dropdown-item" href="#">Logout</a>
									</li>
					</div>
					</ul>
					</li>
					</ul>
			</div>
			</nav>
			<!-- End Navbar -->
		</div>



		<div class="container">
				@RenderBody()

		</div>



		<footer class="footer">
			<div class="container-fluid d-flex justify-content-between">
				<nav class="pull-left">
					<ul class="nav">
						<li class="nav-item">
							<a class="nav-link">
								DataVista
							</a>
						</li>

					</ul>
				</nav>

			</div>
		</footer>


	</div>


	<!--   Core JS Files   -->
	<script src="~/DataVistaTemplate/assets/js/core/jquery-3.7.1.min.js"></script>
	<script src="~/DataVistaTemplate/assets/js/core/popper.min.js"></script>
	<script src="~/DataVistaTemplate/assets/js/core/bootstrap.min.js"></script>

	<!-- jQuery Scrollbar -->
	<script src="~/DataVistaTemplate/assets/js/plugin/jquery-scrollbar/jquery.scrollbar.min.js"></script>
	<!-- jQuery Sparkline -->
	<script src="~/DataVistaTemplate/assets/js/plugin/jquery.sparkline/jquery.sparkline.min.js"></script>
	<!-- Datatables -->
	<script src="~/DataVistaTemplate/assets/js/plugin/datatables/datatables.min.js"></script>
	<!-- Bootstrap Notify -->
	<script src="~/DataVistaTemplate/assets/js/plugin/bootstrap-notify/bootstrap-notify.min.js"></script>
	<!-- Sweet Alert -->
	<script src="~/DataVistaTemplate/assets/js/plugin/sweetalert/sweetalert.min.js"></script>
	<!-- Kaiadmin JS -->
	<script src="~/DataVistaTemplate/assets/js/kaiadmin.min.js"></script>




		@await RenderSectionAsync("Scripts", required: false)
</body>




</html>

DataVista.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DataVista.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DataVista.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - DataVista.Web -@*  <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> *@
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>